#!/bin/bash
# first-time
##################################################################
#	*** P25Link v2.30-3 ***
#	Released: November 13, 2020. Created September 04, 2019.
#	Created by: Juan Carlos Pérez De Castro (Wodie) KM4NNO, XE1F.
#	www.wodielite.com
#	wodielite at mac.com
##################################################################

# See LICENSE file for copyright and license details
# Based on ASL modification by mod4whip N8THN

CONFIGS=/opt/p25link
CONFIGPPATH=$CONFIGS/config.ini
MONTHDAY=$(date +%Y-%m-%d)
DATEEXT=$(date +%Y-%m-%d.%H:%M)
LOGFILE=/tmp/p25link_setup.log



do_check_if_firsttime() {
  if [ -e $CONFIGS/firsttime ]; then
    return
  else
    exit 0
  fi
}

calc_wt_size() {
  echo "doing calc_wt_size" >> $LOGFILE
  WT_HEIGHT=22
  WT_WIDTH=$(tput cols)
  if [ -z "$WT_WIDTH" ] || [ "$WT_WIDTH" -lt 60 ]; then
    WT_WIDTH=80
  fi
  if [ "$WT_WIDTH" -gt 178 ]; then
    WT_WIDTH=120
  fi
  WT_MENU_HEIGHT=$(($WT_HEIGHT-7))
}

#################################################################################
# root/sudo test ################################################################
#################################################################################
check_if_root() {
  echo "check_if_root" >> $LOGFILE
  if [ `whoami` != root ]; then
    whiptail --msgbox "This script must be run as root or with sudo" 20 60 2
    exit 1
  fi
}

#################################################################################
# Functions #####################################################################
#################################################################################
do_config() {
  mkdir -p $CONFIGS/backup/$DATEEXT
  cp -f $CONFIGPPATH   $CONFIGS/backup/$DATEEXT/config.ini

  HARDWAREMODE=$(grep '^HardwareMode =' /$CONFIGS/config.ini | awk -F'=' '{print $2}' | sed 's/|\i//' | sed -e 's/^\(.\{2\}\).*/\1/'|sed 's/ //g')
  HARDWAREMODE=$(whiptail --inputbox "Current Harware Mode is $HARDWAREMODE, enter new Mode.\n
  0 Serial Set if using KM4NNO HDLC to Serial board,
  1 TCP Set if using Cisco router serial port." 12 78 "$HARDWAREMODE" --title "Hardware Mode" 3>&1 1>&2 2>&3)

  MMDVM_ENABLED=$(grep '^MMDVM_Enabled =' /$CONFIGS/config.ini | awk -F'=' '{print $2}' | sed 's/|\i//' | sed -e 's/^\(.\{2\}\).*/\1/'|sed 's/ //g')
  MMDVM_ENABLED=$(whiptail --inputbox "Current MMDVM network is $MMDVM_ENABLED, enter new mode.\n
  0 No (disabled),
  1 Yes (enabled)." 12 78 "$MMDVM_ENABLED" --title "MMDVM Network" 3>&1 1>&2 2>&3)

  P25LINK_ENABLED=$(grep '^P25Link_Enabled =' /$CONFIGS/config.ini | awk -F'=' '{print $2}' | sed 's/|\i//' | sed -e 's/^\(.\{2\}\).*/\1/'|sed 's/ //g')
  P25LINK_ENABLED=$(whiptail --inputbox "Current P25Link network mode is $P25LINK_ENABLED, enter new mode.\n
  0 No (disabled),
  1 Yes (enabled)." 12 78 "$P25LINK_ENABLED" --title "P25Link Network" 3>&1 1>&2 2>&3)

  P25NX_ENABLED=$(grep '^P25NX_Enabled =' /$CONFIGS/config.ini | awk -F'=' '{print $2}' | sed 's/|\i//' | sed -e 's/^\(.\{2\}\).*/\1/'|sed 's/ //g')
  P25NX_ENABLED=$(whiptail --inputbox "Current P25NX network is $P25NX_ENABLED, enter new mode.\n
  0 No (disabled),
  1 Yes (enabled)." 12 78 "$P25NX_ENABLED" --title "P25NX Network" 3>&1 1>&2 2>&3)

  PRIORITYTG=$(grep '^PriorityTG =' /$CONFIGS/config.ini | awk -F'=' '{print $2}' | sed 's/|\i//' | sed -e 's/^\(.\{10\}\).*/\1/'|sed 's/ //g')
  PRIORITYTG=$(whiptail --inputbox "Current Priority TG is $PRIORITYTG enter new Priority TG." 8 78 "$PRIORITYTG" --title "Priority TG" 3>&1 1>&2 2>&3)

  MUTETGTIMEOUT=$(grep '^MuteTGTimeout =' /$CONFIGS/config.ini | awk -F'=' '{print $2}' | sed 's/|\i//' | sed -e 's/^\(.\{9\}\).*/\1/'|sed 's/ //g')
  MUTETGTIMEOUT=$(whiptail --inputbox "Current MuteTGTimeout is $MUTETGTIMEOUT seconds, enter new MuteTGTimeout." 8 78 "$MUTETGTIMEOUT" --title "MuteTGTimeout" 3>&1 1>&2 2>&3)

  HANGTIME=$(grep '^Hangtime =' /$CONFIGS/config.ini | awk -F'=' '{print $2}' | sed 's/|\i//' | sed -e 's/^\(.\{9\}\).*/\1/'|sed 's/ //g')
  HANGTIME=$(whiptail --inputbox "Current Hangtime is $HANGTIME seconds, enter new Hangtime." 8 78 "$HANGTIME" --title "Hangtime" 3>&1 1>&2 2>&3)

  USEVOICEPROMPTS=$(grep '^UseVoicePrompts =' /$CONFIGS/config.ini | awk -F'=' '{print $2}' | sed 's/|\i//' | sed -e 's/^\(.\{2\}\).*/\1/'|sed 's/ //g')
  USEVOICEPROMPTS=$(whiptail --inputbox "Current Use Voice Prompts mode is $USEVOICEPROMPTS, enter new UseVoicePrompts mode.\n
  0 No (disabled),
  1 Yes (enabled)." 12 78 "$USEVOICEPROMPTS" --title "Use Voice Prompts" 3>&1 1>&2 2>&3)

  USELOCALCOURTESYTONE=$(grep '^UseLocalCourtesyTone =' /$CONFIGS/config.ini | awk -F'=' '{print $2}' | sed 's/|\i//' | sed -e 's/^\(.\{2\}\).*/\1/'|sed 's/ //g')
  USELOCALCOURTESYTONE=$(whiptail --inputbox "Current Local Courtesy Tone is $USELOCALCOURTESYTONE, enter new Local Courtesy Tone selection.\n
  0 Disabled,
  1 3Up Tone,
  2 BeeBoo,
  3 Bumblebee,
  4 Nextel,
  5 RC210-9,
  6 RC210-10,
  7 Quindar-Tone-Start,
  8 Quindar-Tone-End,
  9 CustomTone." 20 78 "$USELOCALCOURTESYTONE" --title "Local Courtesy Tone Selection" 3>&1 1>&2 2>&3)

  USEREMOTECOURTESYTONE=$(grep '^UseRemoteCourtesyTone =' /$CONFIGS/config.ini | awk -F'=' '{print $2}' | sed 's/|\i//' | sed -e 's/^\(.\{2\}\).*/\1/'|sed 's/ //g')
  USEREMOTECOURTESYTONE=$(whiptail --inputbox "Current Remote Courtesy Tone is $USEREMOTECOURTESYTONE, enter new Remote Courtesy Tone selection.\n
  0 Disabled,
  1 3Up Tone,
  2 BeeBoo,
  3 Bumblebee,
  4 Nextel,
  5 RC210-9,
  6 RC210-10,
  7 Quindar-Tone-Start,
  8 Quindar-Tone-End,
  9 CustomTone." 20 78 "$USEREMOTECOURTESYTONE" --title "Remote Courtesy Tone Selection" 3>&1 1>&2 2>&3)

  RADIOID=$(grep '^RadioID =' /$CONFIGS/config.ini | awk -F'=' '{print $2}' | sed 's/|\i//' | sed -e 's/^\(.\{9\}\).*/\1/'|sed 's/ //g')
  RADIOID=$(whiptail --inputbox "Current RadioID is $RADIOID, enter new RadioID." 8 78 "$RADIOID" --title "RadioID" 3>&1 1>&2 2>&3)

  CALLSIGN=$(grep '^Callsign =' /$CONFIGS/config.ini | awk -F'=' '{print $2}' | sed 's/|\i//' | sed -e 's/^\(.\{9\}\).*/\1/'|sed 's/ //g')
  CALLSIGN=$(whiptail --inputbox "Current Callsign is $CALLSIGN, enter new Callsign with no suffix." 8 78 "$CALLSIGN" --title "Callsign" 3>&1 1>&2 2>&3)

  SUFFIX=$(grep '^Suffix =' /$CONFIGS/config.ini | awk -F'=' '{print $2}' | sed 's/|\i//' | sed -e 's/^\(.\{3\}\).*/\1/'|sed 's/ //g')
  SUFFIX=$(whiptail --inputbox "Current APRS Suffix is $SUFFIX enter new Suffix." 8 78 "$SUFFIX" --title "APRS Suffix" 3>&1 1>&2 2>&3)

  PASSCODE=$(grep '^Passcode =' /$CONFIGS/config.ini | awk -F'=' '{print $2}' | sed 's/|\i//' | sed -e 's/^\(.\{9\}\).*/\1/'|sed 's/ //g')
  PASSCODE=$(whiptail --inputbox "Current APRS Passcode is $PASSCODE, enter new Passcode." 8 78 "$PASSCODE" --title "APRS Passcode" 3>&1 1>&2 2>&3)

  LATITUDE=$(grep '^Latitude =' /$CONFIGS/config.ini | awk -F'=' '{print $2}' | sed 's/|\i//' | sed -e 's/^\(.\{10\}\).*/\1/')
  LATITUDE=$(whiptail --inputbox "Current Latitude is $LATITUDE, enter new Latitude in decimal degrees." 8 78 "$LATITUDE" --title "Latitude" 3>&1 1>&2 2>&3)

  #LONGITUDE=$(grep '^Longitude =' /$CONFIGS/config.ini | awk -F'=' '{print $2}' | sed 's/|\i//' | sed -e 's/^\(.\{10\}\).*/\1/')
  LONGITUDE=$(grep '^Longitude =' /$CONFIGS/config.ini | awk -F'=' '{print $2}' | sed 's/|\i//' | sed -e 's/^\(.\{10\}\).*/\1/')
  LONGITUDE=$(whiptail --inputbox "Current Longitude is $LONGITUDE, enter new Longitude in decimal degrees." 8 78 "$LONGITUDE" --title "Longitude" 3>&1 1>&2 2>&3)

  SYMBOL=$(grep '^Symbol =' /$CONFIGS/config.ini | awk -F'=' '{print $2}' | sed 's/|\i//' | sed -e 's/^\(.\{3\}\).*/\1/')
  SYMBOL=$(whiptail --inputbox "Current APRS Symbol is $SYMBOL enter new Symbol." 8 78 "$SYMBOL" --title "Symbol" 3>&1 1>&2 2>&3)

  ALTITUDE=$(grep '^Altitude =' /$CONFIGS/config.ini | awk -F'=' '{print $2}' | sed 's/|\i//' | sed -e 's/^\(.\{6\}\).*/\1/'|sed 's/ //g')
  ALTITUDE=$(whiptail --inputbox "Current Altitude is $ALTITUDE, enter new Altitude in meters." 8 78 "$ALTITUDE" --title "Altitude" 3>&1 1>&2 2>&3)

  FREQUENCY=$(grep '^Frequency =' /$CONFIGS/config.ini | awk -F'=' '{print $2}' | sed 's/|\i//' | sed -e 's/^\(.\{10\}\).*/\1/'|sed 's/ //g')
  FREQUENCY=$(whiptail --inputbox "Current Frequency is $FREQUENCY enter new Frequencyin MHz (i.e. 445.000)." 8 78 "$FREQUENCY" --title "Frequency" 3>&1 1>&2 2>&3)

  ACCESSTONE=$(grep '^AccessTone =' /$CONFIGS/config.ini | awk -F'=' '{print $2}' | sed 's/|\i//' | sed -e 's/^\(.\{5\}\).*/\1/'|sed 's/ //g')
  ACCESSTONE=$(whiptail --inputbox "Current Access Tone is $ACCESSTONE, enter new Tone with APRS QSY format. UperCase for 25 KHz bandwidth and lowercase for 12.5 KHz bandwidth.\n T/t for Tone & SQL,\n C/c for Tone up and down\n D/d for Digital tone.\nUse only 3 digits format with no decimanls (i.e. d023 C123)." 12 78 "$ACCESSTONE" --title "Repeater Access Tone" 3>&1 1>&2 2>&3)

  OFFSET=$(grep '^Offset =' /$CONFIGS/config.ini | awk -F'=' '{print $2}' | sed 's/|\i//' | sed -e 's/^\(.\{5\}\).*/\1/')
  OFFSET=$(whiptail --inputbox "Current Offset is $OFFSET enter new Offset preceded with sign (i.e. +500 for UHF -060 for VHF)." 8 78 "$OFFSET" --title "Offset" 3>&1 1>&2 2>&3)

  NAC=$(grep '^NAC =' /$CONFIGS/config.ini | awk -F'=' '{print $2}' | sed 's/|\i//' | sed -e 's/^\(.\{4\}\).*/\1/'|sed 's/ //g')
  NAC=$(whiptail --inputbox "Current NAC is $NAC, enter new NAC." 8 78 "$NAC" --title "NAC" 3>&1 1>&2 2>&3)

  APRSCOMMENT=$(grep '^APRSComment =' /$CONFIGS/config.ini | awk -F'=' '{print $2}' | sed 's/|\i//' | sed -e 's/^\(.\{44\}\).*/\1/' | sed 's/ //g')
  APRSCOMMENT=$(whiptail --inputbox "Current APRS Comment is $APRSCOMMENT, enter new Comment." 8 78 "$APRSCOMMENT" --title "APRS Comment" 3>&1 1>&2 2>&3)

  SITENAME=$(grep '^SiteName =' /$CONFIGS/config.ini | awk -F'=' '{print $2}' | sed 's/|\i//' | sed -e 's/^\(.\{31\}\).*/\1/'|sed 's/ //g')
  SITENAME=$(whiptail --inputbox "Current site name is $SITENAME, enter new name (max 30 char)." 8 78 "$SITENAME" --title "Site Name" 3>&1 1>&2 2>&3)

  SITEINFO=$(grep '^SiteInfo =' /$CONFIGS/config.ini | awk -F'=' '{print $2}' | sed 's/|\i//' | sed -e 's/^\(.\{31\}\).*/\1/'|sed 's/ //g')
  SITEINFO=$(whiptail --inputbox "Current site information is $SITEINFO, enter new information (max 30 char)." 8 78 "$SITEINFO" --title "Site Name" 3>&1 1>&2 2>&3)



  sed -i 's/HardwareMode.*/HardwareMode = '$HARDWAREMODE'/' $CONFIGS/config.ini
  sed -i 's/MMDVM_Enabled.*/MMDVM_Enabled = '$MMDVM_ENABLED'/' $CONFIGS/config.ini
  sed -i 's/P25Link_Enabled.*/P25Link_Enabled = '$P25LINK_ENABLED'/' $CONFIGS/config.ini
  sed -i 's/P25NX_Enabled.*/P25NX_Enabled = '$P25NX_ENABLED'/' $CONFIGS/config.ini
  sed -i 's/PriorityTG.*/PriorityTG = '$PRIORITYTG'/' $CONFIGS/config.ini
  sed -i 's/MuteTGTimeout.*/MuteTGTimeout = '$MUTETGTIMEOUT'/' $CONFIGS/config.ini
  sed -i 's/Hangtime.*/Hangtime = '$HANGTIME'/' $CONFIGS/config.ini
  sed -i 's/UseVoicePrompts.*/UseVoicePrompts = '$USEVOICEPROMPTS'/' $CONFIGS/config.ini
  sed -i 's/UseLocalCourtesyTone.*/UseLocalCourtesyTone = '$USELOCALCOURTESYTONE'/' $CONFIGS/config.ini
  sed -i 's/UseRemoteCourtesyTone.*/UseRemoteCourtesyTone = '$USEREMOTECOURTESYTONE'/' $CONFIGS/config.ini
  sed -i 's/RadioID.*/RadioID = '$RADIOID'/' $CONFIGS/config.ini
  sed -i 's/Callsign.*/Callsign = '$CALLSIGN'/' $CONFIGS/config.ini
  sed -i 's/Suffix.*/Suffix = '$SUFFIX'/' $CONFIGS/config.ini
  sed -i 's/Passcode.*/Passcode = '$PASSCODE'/' $CONFIGS/config.ini
  sed -i 's/Latitude.*/Latitude = '$LATITUDE'/' $CONFIGS/config.ini
  sed -i 's/Longitude.*/Longitude = '$LONGITUDE'/' $CONFIGS/config.ini
  sed -i 's/Symbol.*/Symbol = '$SYMBOL'/' $CONFIGS/config.ini
  sed -i 's/Altitude.*/Altitude = '$ALTITUDE'/' $CONFIGS/config.ini
  sed -i 's/Frequency.*/Frequency = '$FREQUENCY'/' $CONFIGS/config.ini
  sed -i 's/AccessTone.*/AccessTone = '$ACCESSTONE'/' $CONFIGS/config.ini
  sed -i 's/Offset.*/Offset = '$OFFSET'/' $CONFIGS/config.ini
  sed -i 's/NAC.*/NAC = '$NAC'/' $CONFIGS/config.ini
  sed -i 's/APRSComment.*/APRSComment = '$APRSCOMMENT'/' $CONFIGS/config.ini
  sed -i 's/SITEINFO.*/SITEINFO = '$SITEINFO'/' $CONFIGS/config.ini
  sed -i 's/SITEINFO.*/SITEINFO = '$SITEINFO'/' $CONFIGS/config.ini

  P25LINK_RESTART=1
}



#################################################################################
# Main body here ################################################################
#################################################################################
#do_check_if_firsttime
check_if_root
if (whiptail --title "First time setup" --yesno "First time setup.\n\nDo you want to do this now?" --defaultno 15 78) then
  ANSWER=$?
else
  ANSWER=$?
fi

if [ $ANSWER = 1 ]
then
  whiptail --msgbox "You can run this setup at any time later" 8 78
  exit 0
else
  calc_wt_size
  do_config
fi
